### ISSUE TITLE
Default Location (and Python version)

### ISSUE THREAD

**Issue by cmatthewbrooks** [x-j/ps1scriptify#2]
Quickly tested this on itself using an Ubuntu host. By default, it seems to drop the .ps1 file in the parent directory but with a '\' in the name instead of the current directory like the output suggests.

![image](https://user-images.githubusercontent.com/3974104/50818439-e79b9780-1361-11e9-88d9-dc985c4d4024.png)

Also - it seems this only works on Python3, which doesn't bother me but it might be nice to note in the README.

**Comment by x-j** [comment]
Ah, of course. I didn't consider the fact that Unix uses slashes instead of backslashes. I'll get around to fix that soon.
Also adding the note about Python3 to readme, thanks!
